

### Generating a Fake E-commerce Dataset

First, let's create a synthetic dataset to work with. We'll generate 10,000 rows with various e-commerce related fields.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Step 1: Set the scale
num_rows = np.random.randint(100000, 999999)  # Random number of rows between

# Step 2: Generate the raw pieces
order_ids = np.arange(1001, 1001 + num_rows)
customer_ids = np.random.randint(10000, 900000, size=num_rows)
categories = np.random.choice(['Electronics', 'Clothing', 'Home', 'Beauty', 'phone' , 'shaver' , 'protein powder' ], size=num_rows)
quantity_sold = np.random.randint(1, 100, size=num_rows)
item_price = np.round(np.random.uniform(2.0, 5000.0, size=num_rows), 2)

# Step 3: Add your calculations
total_revenue = quantity_sold * item_price
returned = np.random.choice([True, False], size=num_rows, p=[0.1, 0.9])

# Step 4: Pack them into the DataFrame container
df = pd.DataFrame({
    'Order_ID': order_ids,
    'Customer_ID': customer_ids,
    'Category': categories,
    'Quantity_Sold': quantity_sold,
    'Item_Price': item_price,
    'Total_Revenue': total_revenue,
    'Returned': returned
})
#print("--- FIRST 5 ROWS OF YOUR DATASET ---")
#print(df.head(7))

# now pulling out one specific row in whole dataset

# 1. Pull out only the Protein Powder rows
#protein_powder_orders = df.loc[(df['Category'] == 'protein powder') & (df['Item_Price']>10)]

#print("\n--- PINPOINT: ALL PROTEIN POWDER ORDERS ---")
#print(protein_powder_orders.head())

# Deprecated old Matplotlib bar chart to upgrade to advanced Seaborn statistical plots.
#print("Launching Data Visualization Window...")

# 1. Prepare the data group
#category_revenue = df.groupby('Category')['Total_Revenue'].sum().sort_values(ascending=False)

# 2. Setup the canvas size
#plt.figure(figsize=(10, 5))

# 3. Paint the data onto the canvas
#category_revenue.plot(kind='bar', color='red', edgecolor='black')

# 4. Decorate the canvas with human text
#plt.title('Total Revenue Generated by Product Category', fontsize=14, fontweight='bold')
#plt.xlabel('Product Category', fontsize=12)
#plt.ylabel('Total Revenue ($)', fontsize=12)
#plt.xticks(rotation=45)
#plt.grid(axis='y', linestyle='--', alpha=0.7)

# 5. Display the final masterpiece
#plt.tight_layout()
#plt.show()
# now using seaborn for charts
sns.set_theme(style="whitegrid")
print("Launching Advanced Seaborn Windows...")

# Chart 1: Box Plot
plt.figure(figsize=(12, 6))
sns.boxplot(data=df, x='Category', y='Item_Price', palette='Set2', hue='Category', legend=False)
plt.title('Market Price Distribution Analysis Across Categories', fontsize=14, fontweight='bold')
plt.xticks(rotation=30)
plt.tight_layout()
plt.show() # <-- Seaborn uses Matplotlib's show button to pop the window open!